layout_spectrum: 0.8763441
typography_spectrum: 0.7279182
color:
  saturation: 0.7777778
  brandStrength: 0.483871
  lightness: 0.1845878
  brandColors:
    - '#090504'
    - '#75767A'
    - '#DBBE92'
    - '#4D4A4B'
    - '#FFE9CE'
  rhythmicContrast: 0.3293594
name: Artmony
