name: Artmony
favicon: null
layout_spectrum: 0.8763441
typography_spectrum: 0.7279182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090504'
    - '#75767A'
    - '#DBBE92'
    - '#4D4A4B'
    - '#FFE9CE'
  brandStrength: 0.483871
  lightness: 0.1845878
  saturation: 0.7777778
  rhythmicContrast: 0.3293594
purpose: []
